In [1]:
import numpy as np
from numpy import dtype
from tornado.autoreload import start

In [2]:
data = [1,2,3]
print(f'data的内存地址{id(data)}')

arr1=np.array(data) #从数组列表创建arry tips: 包解释 create an arry
print(arr1)
print(type(arr1))
print(f"arr1的内存地址{id(arr1)}")

data的内存地址130869863582272
[1 2 3]
<class 'numpy.ndarray'>
arr1的内存地址130869864839856


In [3]:
arr2 = np.asarray(data)  #tips:包解释是Convert the input to an array.
print(arr2)
print(type(arr2))
print(f"arr2的内存地址{id(arr2)}")

[1 2 3]
<class 'numpy.ndarray'>
arr2的内存地址130869864839664


In [4]:
arr3 = np.asarray(arr2)
print(arr3)
print(type(arr3))
print(f"arr3的内存地址{id(arr3)}")

[1 2 3]
<class 'numpy.ndarray'>
arr3的内存地址130869864839664


这也就验证了猜想,也就是说asarry不会改变原来的内存地址,而只是对原来的进行了转化,但是arry则会新建一个新的ndarry并开辟新的内存地址

In [6]:
arr = np.zeros((2,3) ,dtype=int) #tips:如果不指定dtype那么默认是浮点数
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
arr = np.ones((2,3) ,dtype=int)
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
arr = np.zeros_like(arr) #tips:传一个数组过来,给你生成个形状一样的但是0填充的数组
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
arr = np.empty_like(arr)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
arr=np.full((2,3),6)
arr

array([[6, 6, 6],
       [6, 6, 6]])

In [12]:
arr = np.full_like(arr,8)
arr

array([[8, 8, 8],
       [8, 8, 8]])

In [13]:
arr = np.arange(start=1,stop=10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.arange(start=1,stop=9,step=2)
arr

array([1, 3, 5, 7])

In [15]:
np.linspace(0,10,5) #tips:等差数列,生成0-10共5个等差数列

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.linspace(0,10,5,endpoint=True)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.linspace(0,10,5,endpoint=False) #tips：不包含stop

array([0., 2., 4., 6., 8.])

In [21]:
np.logspace(start=2,stop=5,num=2,base=2)

array([ 4., 32.])

$ {base}^{start} 到{base}^{stop}$共num个数

In [25]:
np.random.rand(2,3) #tips:生成2行3列数组,默认填充0-1(不包含1)之间的浮点数

array([[0.35946588, 0.97288021, 0.5149911 ],
       [0.80910673, 0.0999404 , 0.71280983]])

In [24]:
np.random.randint(0,10,(3,3)) #tips:生成一个3x3的矩阵,随机数字填充,范围是0-10(不包括10)

array([[0, 1, 4],
       [8, 9, 5],
       [7, 9, 0]])

In [26]:
np.random.uniform(low=0,high=10,size=(3,3)) #返回给定形状的数组,从低位到高位上均匀分布的随机浮点数

array([[1.04267678, 0.20219899, 2.17549075],
       [6.67168322, 2.54569353, 2.90059161],
       [9.90747225, 1.64613085, 0.36080091]])

In [27]:
np.random.randn(2,3) #返回给定形状的数组,用标准正态分布(均值为0,标准差为1)的随即样本填充

array([[ 0.27233958, -0.37688198,  1.05018272],
       [ 2.43616165, -0.49424496, -0.84708861]])

In [28]:
arr1 = np.matrix("1,2;3,4")
arr1

matrix([[1, 2],
        [3, 4]])

In [29]:
print(type(arr1))

<class 'numpy.matrix'>


## 数据类型

In [30]:
np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float64)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [31]:
np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="i8")

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])