In [1]:
import numpy  as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[1:3]

array([1, 2])

In [4]:
arr[1:5:2]  #tips:arr[start:stop(不包含):step]

array([1, 3])

In [6]:
arr[slice(1,5,2)] #tips:和上面效果一致

array([1, 3])

In [10]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [14]:
arr2 = np.array([[i for i in range(1,6)],[j for j in range(6,11)],[k for k in range(11,16)]])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
arr2[:2,0:3] #tips:取出前两行前三列

array([[1, 2, 3],
       [6, 7, 8]])

In [17]:
arr2[:,-2:] #tips:取出最后两列

array([[ 4,  5],
       [ 9, 10],
       [14, 15]])

In [18]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])