In [1]:
import numpy as np

In [2]:
np.abs(-5)

np.int64(5)

In [4]:
arr1 = np.array([[1,-3,2,4,3.5],[2,-9,6,3.3,8],[9,0,-8,9.2,4]])
arr1

array([[ 1. , -3. ,  2. ,  4. ,  3.5],
       [ 2. , -9. ,  6. ,  3.3,  8. ],
       [ 9. ,  0. , -8. ,  9.2,  4. ]])

In [5]:
absarr1 = np.abs(arr1)
absarr1

array([[1. , 3. , 2. , 4. , 3.5],
       [2. , 9. , 6. , 3.3, 8. ],
       [9. , 0. , 8. , 9.2, 4. ]])

In [6]:
cellarr = np.ceil(arr1)
cellarr

array([[ 1., -3.,  2.,  4.,  4.],
       [ 2., -9.,  6.,  4.,  8.],
       [ 9.,  0., -8., 10.,  4.]])

In [7]:
floorarr = np.floor(arr1) #tips:向下取整
floorarr

array([[ 1., -3.,  2.,  4.,  3.],
       [ 2., -9.,  6.,  3.,  8.],
       [ 9.,  0., -8.,  9.,  4.]])

In [8]:
rintarr = np.rint(arr1) #tips：四舍六入五成双
rintarr

array([[ 1., -3.,  2.,  4.,  4.],
       [ 2., -9.,  6.,  3.,  8.],
       [ 9.,  0., -8.,  9.,  4.]])

In [9]:
type(np.nan)

float

In [10]:
arr3  = np.array([[1,2,3],[4,5,6]])

In [11]:
np.multiply(arr3,5)#tips:如果第二个参数传入的是数字的花那就是二维数组中的每个元素*数字

array([[ 5, 10, 15],
       [20, 25, 30]])

In [12]:
arr4=np.array([[2,2,2],[3,3,3]])

np.multiply(arr3,arr4) #tips:数组和数组间的元素相乘

array([[ 2,  4,  6],
       [12, 15, 18]])

In [13]:
np.where(arr3>4,11,22)  #tips:三元运算

array([[22, 22, 22],
       [22, 11, 11]])

In [14]:
np.mean(arr3)

np.float64(3.5)

In [16]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.max(arr3)

np.int64(6)

In [18]:
np.max(arr3,axis=0) #tips:统计每一列的最大值

array([4, 5, 6])

In [15]:
np.max(arr3,axis=1) #tips:统计每一行的最大值

array([3, 6])

In [20]:
np.std(arr3) #tips:统计标准差

np.float64(1.707825127659933)

In [19]:
np.var(arr3) #tips:统计方差

np.float64(2.9166666666666665)

In [22]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.argmin(arr3,axis=0) #tips:按列找最小的索引下标

array([0, 0, 0])

In [23]:
np.argmin(arr3,axis=1) #tips:按行找最小值的索引下标


array([0, 0])

In [24]:
np.argmax(arr3,axis=0)

array([1, 1, 1])

In [25]:
np.argmax(arr3,axis=1)

array([2, 2])

In [26]:
np.cumsum(arr3,axis=0) #tips:返回一个数组,每个元素都是之前所有元素的累加和

array([[1, 2, 3],
       [5, 7, 9]])

In [27]:
np.cumsum(arr3,axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])