In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [3]:
np.mean(arr)

np.float64(5.5)

In [4]:
np.sum(arr)

np.int64(55)

In [5]:
np.max(arr)

np.int64(10)

In [6]:
np.max(arr,axis=0) #tips:按列取最大

array([ 6,  7,  8,  9, 10])

In [7]:
np.max(arr,axis=1) #tips:按行取最大

array([ 5, 10])

In [8]:
np.argmax(arr)

np.int64(9)

In [9]:
np.argmax(arr,axis=0)

array([1, 1, 1, 1, 1])

In [10]:
np.argmax(arr,axis=1)

array([4, 4])

In [11]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [12]:
np.cumsum(arr,axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 7,  9, 11, 13, 15]])

In [13]:
np.cumsum(arr,axis=1)

array([[ 1,  3,  6, 10, 15],
       [ 6, 13, 21, 30, 40]])