In [1]:
import numpy as  np
from sympy import true

np.any()至少有一个满足条件,就返回true
np.all()所有的元素都满足条件,才返回true

In [2]:
arr = np.array([[1,3,2,6,5],[8,6,4,9,0]])

In [3]:
np.any(arr)

np.True_

In [4]:
np.any(arr>1)

np.True_

In [5]:
np.any(arr>100)

np.False_

In [6]:
np.all(arr>=0)

np.True_

In [7]:
np.all(arr>0)

np.False_

排序函数

In [9]:
arr

array([[1, 3, 2, 6, 5],
       [8, 6, 4, 9, 0]])

In [8]:
np.sort(arr) #tips:默认按行升序排序

array([[1, 2, 3, 5, 6],
       [0, 4, 6, 8, 9]])

In [12]:
np.sort(arr,axis=0) #tips:按列升序排序

array([[1, 3, 2, 6, 0],
       [8, 6, 4, 9, 5]])

In [13]:
np.sort(arr,axis=1) #tips：按行升序排序

array([[1, 2, 3, 5, 6],
       [0, 4, 6, 8, 9]])

还有原地排序,这样就不会返回新的数组

In [14]:
arr.sort()

In [15]:
arr

array([[1, 2, 3, 5, 6],
       [0, 4, 6, 8, 9]])

也可以传入axis,但是要注意,原地排序会改变原来的数组

去重复

In [16]:
arr1 = np.random.randint(0,10,(3,3))
arr1

array([[4, 8, 5],
       [8, 1, 0],
       [4, 7, 2]])

In [17]:
print(np.unique(arr1))

[0 1 2 4 5 7 8]
