In [1]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[3,5,7],[9,9,6],[3,8,6]])

In [4]:
arr1+arr2

array([[ 4,  7, 10],
       [13, 14, 12],
       [10, 16, 15]])

In [5]:
arr1*arr2

array([[ 3, 10, 21],
       [36, 45, 36],
       [21, 64, 54]])

上面是形状相同的,但是如果是不同形状呢?

ndarry是有复杂广播能力的,它允许在不同形状的数组之间进行元素级运算

规则1:如果俩数组的维度不相同,那么小维度数组的形状会在最左边补1

In [6]:
arr1  = np.array([1,2,3]) #tips:形状为1维数组
arr1

array([1, 2, 3])

In [12]:
arr1.shape #tips:3列

(3,)

In [7]:
arr2 = np.array([[4],[5],[6]]) #tips:3行1列的二维数组
arr2

array([[4],
       [5],
       [6]])

In [13]:
arr2.shape #tips:3行1列

(3, 1)

对arr1应用规则,在其形状3列(3,)最左边补1，变成(1,3) 1行3列

In [8]:
arr1+arr2

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

$$
  arr1 = \begin{bmatrix}
    1 & 2 & 3\end{bmatrix}\
  arr2 = \begin{bmatrix}
    4\\
    5\\
    6
  \end{bmatrix}
$$

规则2:如果俩数组形状在任何一个维度都不匹配,那么数组的形状会沿着维度大小(元素个数)为1的维度开始扩展,直到所有维度都一样

$$
  arr1 = \begin{bmatrix}
    1 & 2 & 3 \\
    1 & 2 & 3 \\
    1 & 2 & 3 \\
  \end{bmatrix}
  arr2 = \begin{bmatrix}
    4 & 5 & 6 \\
    4 & 5 & 6 \\
    4 & 5 & 6 \\
  \end{bmatrix}
$$

规则3:如果俩个数组的形状在任何一个维度上都不匹配,并且没有任何一个维度大小等于1,那么会引发异常