In [1]:
import numpy as np

之前都是ndarry对位计算，还不算是矩阵运算

In [7]:
m1 = np.matrix([[1,2,3],[4,5,6]])
m2 = np.matrix([[6,5],[4,3],[2,1]])

In [8]:
mat1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [9]:
mat2

matrix([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])

In [10]:
np.dot(mat1,mat2)

matrix([[ 66,  72,  78],
        [156, 171, 186]])